package com.acme.clipcascade;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.util.UUID;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

class ClipboardHistorySchemaTests {
    @Test
    void existingHistoryGainsUnpinnedDefaultWithoutLosingDataAndMigrationIsRepeatable() throws Exception {
        try (var connection = DriverManager.getConnection(
                "jdbc:h2:mem:legacy-history-" + UUID.randomUUID() + ";MODE=PostgreSQL", "sa", "")) {
            try (var statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE clipboard_history (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(255) NOT NULL,
                            device_id VARCHAR(64),
                            payload_type VARCHAR(50) NOT NULL,
                            payload CLOB,
                            payload_size BIGINT,
                            created_at BIGINT NOT NULL
                        )
                        """);
                statement.execute("""
                        INSERT INTO clipboard_history
                            (username, device_id, payload_type, payload, payload_size, created_at)
                        VALUES ('legacy-owner', 'legacy-device', 'text', 'preserved synthetic clip', 24, 1)
                        """);
            }

            var schema = new ResourceDatabasePopulator(new ClassPathResource("schema.sql"));
            schema.populate(connection);
            schema.populate(connection);

            try (var statement = connection.createStatement();
                    var rows = statement.executeQuery("SELECT username, payload, pinned FROM clipboard_history")) {
                assertThat(rows.next()).isTrue();
                assertThat(rows.getString("username")).isEqualTo("legacy-owner");
                assertThat(rows.getString("payload")).isEqualTo("preserved synthetic clip");
                assertThat(rows.getBoolean("pinned")).isFalse();
                assertThat(rows.next()).isFalse();
            }
        }
    }
}
